spring:
  datasource:
    url: jdbc:mysql://localhost:3306/golden_shoe?useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Warsaw&autoReconnect=true&characterEncoding=UTF-8&useUnicode=yes
    username: root
    password: password108
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: patrykblakala108java@gmail.com
    password: sitarama108@
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          #          auth: true
          ssl:
            trust: smtp.gmail.com
